Repository DEPthes/3rd-MVP-NS-Server, pull requests merged in 2024-08, with the labels that each got.

#1 [FEAT]: 기본 세팅 및 auth 관련 구현
  .gitignore
  build.gradle
  src/main/java/depth/mvp/ns/NsApplication.java
  src/main/java/depth/mvp/ns/domain/auth/controller/AuthController.java
  src/main/java/depth/mvp/ns/domain/auth/dto/request/CheckNicknameReq.java
  src/main/java/depth/mvp/ns/domain/auth/dto/request/CheckUsernameReq.java
  src/main/java/depth/mvp/ns/domain/auth/dto/request/SignInReq.java
  src/main/java/depth/mvp/ns/domain/auth/dto/request/SignUpReq.java
  src/main/java/depth/mvp/ns/domain/auth/dto/response/CheckDuplicateRes.java
  src/main/java/depth/mvp/ns/domain/auth/service/AuthService.java
  src/main/java/depth/mvp/ns/domain/auth/token/domain/RefreshToken.java
  src/main/java/depth/mvp/ns/domain/auth/token/domain/repository/RefreshTokenRepository.java
  src/main/java/depth/mvp/ns/domain/auth/token/dto/RefreshTokenReq.java
  src/main/java/depth/mvp/ns/domain/auth/token/dto/TokenDto.java
  src/main/java/depth/mvp/ns/domain/board/controller/BoardController.java
  src/main/java/depth/mvp/ns/domain/board/domain/Board.java
  src/main/java/depth/mvp/ns/domain/board/domain/repository/BoardRepository.java
  src/main/java/depth/mvp/ns/domain/board/service/BoardService.java
  src/main/java/depth/mvp/ns/domain/board_like/domain/BoardLike.java
  src/main/java/depth/mvp/ns/domain/board_like/domain/repository/BoardLikeRepository.java
  src/main/java/depth/mvp/ns/domain/common/BaseEntity.java
  src/main/java/depth/mvp/ns/domain/common/Status.java
  src/main/java/depth/mvp/ns/domain/report/controller/ReportController.java
  src/main/java/depth/mvp/ns/domain/report/domain/Report.java
  src/main/java/depth/mvp/ns/domain/report/domain/repository/ReportRepository.java
  src/main/java/depth/mvp/ns/domain/report/service/ReportService.java
  src/main/java/depth/mvp/ns/domain/report_detail/domain/ReportDetail.java
  src/main/java/depth/mvp/ns/domain/report_detail/domain/ReportType.java
  src/main/java/depth/mvp/ns/domain/report_detail/domain/repository/ReportDetailRepository.java
  src/main/java/depth/mvp/ns/domain/s3/service/S3Uploader.java
  src/main/java/depth/mvp/ns/domain/theme/domain/Theme.java
  src/main/java/depth/mvp/ns/domain/theme/domain/repository/ThemeRepository.java
  src/main/java/depth/mvp/ns/domain/theme_like/domain/ThemeLike.java
  src/main/java/depth/mvp/ns/domain/theme_like/domain/repository/ThemeLikeRepository.java
  src/main/java/depth/mvp/ns/domain/user/controller/UserController.java
  src/main/java/depth/mvp/ns/domain/user/domain/Role.java
  src/main/java/depth/mvp/ns/domain/user/domain/User.java
  src/main/java/depth/mvp/ns/domain/user/domain/repository/UserRepository.java
  src/main/java/depth/mvp/ns/domain/user/dto/response/MyPageRes.java
  src/main/java/depth/mvp/ns/domain/user/service/UserService.java
  src/main/java/depth/mvp/ns/global/config/S3Config.java
  src/main/java/depth/mvp/ns/global/config/security/SecurityConfig.java
  src/main/java/depth/mvp/ns/global/config/security/filter/JwtFilter.java
  src/main/java/depth/mvp/ns/global/config/security/handler/JwtAccessDeniedHandler.java
  src/main/java/depth/mvp/ns/global/config/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/depth/mvp/ns/global/config/security/token/CurrentUser.java
  src/main/java/depth/mvp/ns/global/config/security/token/CustomUserDetails.java
  src/main/java/depth/mvp/ns/global/config/security/token/CustomUserDetailsService.java
  src/main/java/depth/mvp/ns/global/config/security/token/TokenProvider.java
  src/main/java/depth/mvp/ns/global/error/DefaultException.java
  src/main/java/depth/mvp/ns/global/error/DefaultNullPointerException.java
  src/main/java/depth/mvp/ns/global/error/InvalidParameterException.java
  src/main/java/depth/mvp/ns/global/payload/ApiResponse.java
  src/main/java/depth/mvp/ns/global/payload/DefaultAssert.java
  src/main/java/depth/mvp/ns/global/payload/ErrorCode.java
  src/main/resources/application-springdoc.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: docs📄, feature✨

#3 [FEAT] :sparkles: 누적 N포인트 TOP3 조회 기능 구현
  build.gradle
  src/main/java/depth/mvp/ns/domain/user/controller/UserController.java
  src/main/java/depth/mvp/ns/domain/user/domain/RankingType.java
  src/main/java/depth/mvp/ns/domain/user/domain/repository/UserQueryDslRepository.java
  src/main/java/depth/mvp/ns/domain/user/domain/repository/UserQueryDslRepositoryImpl.java
  src/main/java/depth/mvp/ns/domain/user/domain/repository/UserRepository.java
  src/main/java/depth/mvp/ns/domain/user/dto/response/UserRankingRes.java
  src/main/java/depth/mvp/ns/domain/user/service/UserService.java
  src/main/java/depth/mvp/ns/global/config/QuerydslConfig.java
Labels: feature✨

#5 [FEAT] 글 게시, 임시저장, 수정, 삭제 기능 구현
  src/main/java/depth/mvp/ns/domain/board/controller/BoardController.java
  src/main/java/depth/mvp/ns/domain/board/domain/Board.java
  src/main/java/depth/mvp/ns/domain/board/domain/repository/BoardRepository.java
  src/main/java/depth/mvp/ns/domain/board/dto/request/PublishReq.java
  src/main/java/depth/mvp/ns/domain/board/dto/request/SaveDraftReq.java
  src/main/java/depth/mvp/ns/domain/board/dto/request/UpdateReq.java
  src/main/java/depth/mvp/ns/domain/board/service/BoardService.java
  src/main/java/depth/mvp/ns/domain/common/BaseEntity.java
Labels: feature✨

#10 [FEAT] 오늘의 주제 조회 기능 구현
  src/main/java/depth/mvp/ns/domain/theme/controller/ThemeController.java
  src/main/java/depth/mvp/ns/domain/theme/domain/repository/ThemeRepository.java
  src/main/java/depth/mvp/ns/domain/theme/dto/response/TodayThemeRes.java
  src/main/java/depth/mvp/ns/domain/theme/service/ThemeService.java
  src/main/java/depth/mvp/ns/global/config/security/SecurityConfig.java
Labels: feature✨

#6 [FEAT] :sparkles: N보고서 생성 기능 구현
  build.gradle
  src/main/java/depth/mvp/ns/NsApplication.java
  src/main/java/depth/mvp/ns/domain/board/domain/repository/BoardQueryDslRepository.java
  src/main/java/depth/mvp/ns/domain/board/domain/repository/BoardQueryDslRepositoryImpl.java
  src/main/java/depth/mvp/ns/domain/board/domain/repository/BoardRepository.java
  src/main/java/depth/mvp/ns/domain/report/controller/ReportController.java
  src/main/java/depth/mvp/ns/domain/report/domain/Report.java
  src/main/java/depth/mvp/ns/domain/report/domain/WordCount.java
  src/main/java/depth/mvp/ns/domain/report/domain/repository/WordCountRepository.java
  src/main/java/depth/mvp/ns/domain/report/service/CloudImageGenerator.java
  src/main/java/depth/mvp/ns/domain/report/service/ColorCombinations.java
  src/main/java/depth/mvp/ns/domain/report/service/ReportService.java
  src/main/java/depth/mvp/ns/domain/report_detail/domain/ReportDetail.java
  src/main/java/depth/mvp/ns/domain/s3/service/S3Uploader.java
  src/main/java/depth/mvp/ns/domain/theme/domain/repository/ThemeRepository.java
  src/main/java/depth/mvp/ns/global/config/security/SecurityConfig.java
Labels: feature✨

#12 [FIX] 중복 체크 관련 로직 수정
  src/main/java/depth/mvp/ns/domain/auth/controller/AuthController.java
  src/main/java/depth/mvp/ns/domain/auth/dto/request/CheckNicknameReq.java
  src/main/java/depth/mvp/ns/domain/auth/dto/request/CheckUsernameReq.java
  src/main/java/depth/mvp/ns/domain/auth/service/AuthService.java
  src/main/java/depth/mvp/ns/domain/user/controller/UserController.java
  src/main/java/depth/mvp/ns/domain/user/service/UserService.java
  src/main/java/depth/mvp/ns/global/config/WebMvcConfig.java
  src/main/java/depth/mvp/ns/global/config/security/SecurityConfig.java
Labels: refactor🔨, fix🔥

#13 [DEPLOY]
  build.gradle
  src/main/java/depth/mvp/ns/NsApplication.java
  src/main/java/depth/mvp/ns/domain/auth/controller/AuthController.java
  src/main/java/depth/mvp/ns/domain/auth/dto/request/CheckNicknameReq.java
  src/main/java/depth/mvp/ns/domain/auth/dto/request/CheckUsernameReq.java
  src/main/java/depth/mvp/ns/domain/auth/service/AuthService.java
  src/main/java/depth/mvp/ns/domain/board/domain/repository/BoardQueryDslRepository.java
  src/main/java/depth/mvp/ns/domain/board/domain/repository/BoardQueryDslRepositoryImpl.java
  src/main/java/depth/mvp/ns/domain/board/domain/repository/BoardRepository.java
  src/main/java/depth/mvp/ns/domain/report/controller/ReportController.java
  src/main/java/depth/mvp/ns/domain/report/domain/Report.java
  src/main/java/depth/mvp/ns/domain/report/domain/WordCount.java
  src/main/java/depth/mvp/ns/domain/report/domain/repository/WordCountRepository.java
  src/main/java/depth/mvp/ns/domain/report/service/CloudImageGenerator.java
  src/main/java/depth/mvp/ns/domain/report/service/ColorCombinations.java
  src/main/java/depth/mvp/ns/domain/report/service/ReportService.java
  src/main/java/depth/mvp/ns/domain/report_detail/domain/ReportDetail.java
  src/main/java/depth/mvp/ns/domain/s3/service/S3Uploader.java
  src/main/java/depth/mvp/ns/domain/theme/controller/ThemeController.java
  src/main/java/depth/mvp/ns/domain/theme/domain/repository/ThemeRepository.java
  src/main/java/depth/mvp/ns/domain/theme/dto/response/TodayThemeRes.java
  src/main/java/depth/mvp/ns/domain/theme/service/ThemeService.java
  src/main/java/depth/mvp/ns/domain/user/controller/UserController.java
  src/main/java/depth/mvp/ns/domain/user/service/UserService.java
  src/main/java/depth/mvp/ns/global/config/WebMvcConfig.java
  src/main/java/depth/mvp/ns/global/config/security/SecurityConfig.java
Labels: feature✨, fix🔥

#24 [FEAT] 마이페이지 및 좋아요 기능 구현
  .gitignore
  src/main/java/depth/mvp/ns/domain/auth/controller/AuthController.java
  src/main/java/depth/mvp/ns/domain/board/controller/BoardController.java
  src/main/java/depth/mvp/ns/domain/board/dto/response/BoardLikeRes.java
  src/main/java/depth/mvp/ns/domain/board/service/BoardService.java
  src/main/java/depth/mvp/ns/domain/board_like/domain/BoardLike.java
  src/main/java/depth/mvp/ns/domain/board_like/domain/repository/BoardLikeRepository.java
  src/main/java/depth/mvp/ns/domain/theme/controller/ThemeController.java
  src/main/java/depth/mvp/ns/domain/theme/dto/response/ThemeLikeRes.java
  src/main/java/depth/mvp/ns/domain/theme/service/ThemeService.java
  src/main/java/depth/mvp/ns/domain/theme_like/domain/repository/ThemeLikeRepository.java
  src/main/java/depth/mvp/ns/domain/user/controller/UserController.java
  src/main/java/depth/mvp/ns/domain/user/domain/User.java
  src/main/java/depth/mvp/ns/domain/user/dto/request/CheckPasswordReq.java
  src/main/java/depth/mvp/ns/domain/user/dto/request/UpdateNicknameReq.java
  src/main/java/depth/mvp/ns/domain/user/dto/response/BoardLikeByUserRes.java
  src/main/java/depth/mvp/ns/domain/user/dto/response/PageBoardLikeRes.java
  src/main/java/depth/mvp/ns/domain/user/service/UserLikeService.java
  src/main/java/depth/mvp/ns/domain/user/service/UserService.java
  src/main/java/depth/mvp/ns/global/payload/PageInfo.java
Labels: feature✨, fix🔥

#28 [FEAT] 내 게시글 조회 및 검색, 포인트 저장 구현
  src/main/java/depth/mvp/ns/domain/board/domain/Board.java
  src/main/java/depth/mvp/ns/domain/board/domain/repository/BoardRepository.java
  src/main/java/depth/mvp/ns/domain/board/service/BoardService.java
  src/main/java/depth/mvp/ns/domain/board_like/domain/repository/BoardLikeRepository.java
  src/main/java/depth/mvp/ns/domain/point/domain/Point.java
  src/main/java/depth/mvp/ns/domain/point/domain/repository/PointRepository.java
  src/main/java/depth/mvp/ns/domain/theme/service/ThemeService.java
  src/main/java/depth/mvp/ns/domain/theme_like/domain/repository/ThemeLikeRepository.java
  src/main/java/depth/mvp/ns/domain/user/controller/UserController.java
  src/main/java/depth/mvp/ns/domain/user/controller/UserLikeController.java
  src/main/java/depth/mvp/ns/domain/user/dto/response/MyBoardRes.java
  src/main/java/depth/mvp/ns/domain/user/dto/response/PageBoardLikeRes.java
  src/main/java/depth/mvp/ns/domain/user/dto/response/PageRes.java
  src/main/java/depth/mvp/ns/domain/user/dto/response/ThemeLikeByUserRes.java
  src/main/java/depth/mvp/ns/domain/user/service/UserLikeService.java
Labels: feature✨

#31 [FEAT] :sparkles: 날짜 별 point transaction 쿼리문 작성
  src/main/java/depth/mvp/ns/domain/report/service/ReportService.java
  src/main/java/depth/mvp/ns/domain/user/domain/repository/UserQueryDslRepositoryImpl.java
Labels: feature✨

#33 [FIX] Point 엔티티명 변경
  src/main/java/depth/mvp/ns/domain/board/service/BoardService.java
  src/main/java/depth/mvp/ns/domain/report/service/ReportService.java
  src/main/java/depth/mvp/ns/domain/theme/service/ThemeService.java
  src/main/java/depth/mvp/ns/domain/user/domain/repository/UserQueryDslRepositoryImpl.java
  src/main/java/depth/mvp/ns/domain/user_point/domain/UserPoint.java
  src/main/java/depth/mvp/ns/domain/user_point/domain/repository/UserPointRepository.java
Labels: fix🔥

#39 [FIX] 주제 및 게시글 좋아요 기능 로직 수정
  src/main/java/depth/mvp/ns/domain/board/service/BoardService.java
  src/main/java/depth/mvp/ns/domain/theme/service/ThemeService.java
  src/main/java/depth/mvp/ns/domain/user_point/domain/repository/UserPointRepository.java
Labels: fix🔥

#41 [FEAT] :hammer: 프론트 요구사항 반영
  src/main/java/depth/mvp/ns/domain/report/dto/response/ReportRes.java
  src/main/java/depth/mvp/ns/domain/report/service/ReportService.java
  src/main/java/depth/mvp/ns/domain/user/domain/repository/UserQueryDslRepositoryImpl.java
Labels: feature✨, fix🔥

#45 [REFACTOR] page size 일괄 수정
  src/main/java/depth/mvp/ns/domain/theme/controller/ThemeController.java
  src/main/java/depth/mvp/ns/domain/user/controller/UserController.java
  src/main/java/depth/mvp/ns/domain/user/controller/UserLikeController.java
  src/main/java/depth/mvp/ns/domain/user/service/UserLikeService.java
Labels: feature✨, refactor🔨

#51 [FEAT] 내 글 조회 및 검색 시 좋아요 여부 추가
  src/main/java/depth/mvp/ns/domain/auth/dto/request/SignUpReq.java
  src/main/java/depth/mvp/ns/domain/board/domain/Board.java
  src/main/java/depth/mvp/ns/domain/board_like/domain/repository/BoardLikeRepository.java
  src/main/java/depth/mvp/ns/domain/user/dto/request/UpdateNicknameReq.java
  src/main/java/depth/mvp/ns/domain/user/dto/response/MyBoardRes.java
  src/main/java/depth/mvp/ns/domain/user/service/UserLikeService.java
Labels: feature✨, refactor🔨

#53 [FIX] 리포트 관련 오류 수정
  src/main/java/depth/mvp/ns/domain/board/domain/repository/BoardQueryDslRepository.java
  src/main/java/depth/mvp/ns/domain/board/domain/repository/BoardQueryDslRepositoryImpl.java
  src/main/java/depth/mvp/ns/domain/report/dto/response/PrevReportRes.java
  src/main/java/depth/mvp/ns/domain/report/dto/response/ReportRes.java
  src/main/java/depth/mvp/ns/domain/report/service/ReportService.java
  src/main/java/depth/mvp/ns/domain/report_detail/domain/ReportDetail.java
  src/main/java/depth/mvp/ns/domain/user/controller/UserController.java
  src/main/java/depth/mvp/ns/domain/user/dto/response/UserProfileRes.java
  src/main/java/depth/mvp/ns/domain/user/service/UserService.java
Labels: fix🔥

#55 [FIX] 게시글 좋아요 취소 오류 수정
  src/main/java/depth/mvp/ns/domain/board/dto/response/BoardDetailRes.java
  src/main/java/depth/mvp/ns/domain/board/service/BoardService.java
Labels: fix🔥

#57 [FIX] isLiked 에러 수정, 보고서 쿼리 에러 수정
  src/main/java/depth/mvp/ns/domain/board/domain/repository/BoardQueryDslRepository.java
  src/main/java/depth/mvp/ns/domain/board/domain/repository/BoardQueryDslRepositoryImpl.java
  src/main/java/depth/mvp/ns/domain/board/domain/repository/BoardRepository.java
  src/main/java/depth/mvp/ns/domain/report/dto/response/PrevReportRes.java
  src/main/java/depth/mvp/ns/domain/report/service/ReportService.java
  src/main/java/depth/mvp/ns/domain/report_detail/domain/repository/ReportDetailQueryDslRepositoryImpl.java
  src/main/java/depth/mvp/ns/domain/user/controller/UserController.java
  src/main/java/depth/mvp/ns/domain/user/service/UserService.java
Labels: fix🔥

#63 [FIX] isPublished true 조건 추가
  src/main/java/depth/mvp/ns/domain/board/domain/repository/BoardQueryDslRepositoryImpl.java
  src/main/java/depth/mvp/ns/domain/board/domain/repository/BoardRepository.java
  src/main/java/depth/mvp/ns/domain/report/domain/repository/ReportQueryDslRepositoryImpl.java
  src/main/java/depth/mvp/ns/domain/report/service/ReportService.java
Labels: fix🔥

#77 [FIX] nreport 날짜 필터링 추가
  src/main/java/depth/mvp/ns/domain/board/domain/repository/BoardQueryDslRepository.java
  src/main/java/depth/mvp/ns/domain/board/domain/repository/BoardQueryDslRepositoryImpl.java
  src/main/java/depth/mvp/ns/domain/report/service/ReportService.java
Labels: fix🔥

#84 [FIX] report 조회 시 title 오류 수정
  src/main/java/depth/mvp/ns/domain/report/service/ReportService.java
Labels: fix🔥

#87 [FEAT]: 게시글 상세 조회 시 응답 추가
  src/main/java/depth/mvp/ns/domain/board/dto/response/BoardDetailRes.java
  src/main/java/depth/mvp/ns/domain/board/service/BoardService.java
  src/main/java/depth/mvp/ns/domain/report_detail/domain/repository/ReportDetailRepository.java
Labels: feature✨, fix🔥
